ticket_6
amaanmughal/nc-games-frontend pull request #4
Opened 2023-06-01 13:21 UTC by amaanmughal

the game logo is the home button

2023-06-01 15:02 UTC, Keb84 requested changes
At the moment I am getting an error in the console when a review has no comments. Please take a look 👀 and fix this then resend a PR 🙂

2023-06-02 08:03 UTC, MrMcSnail approved these changes
I'd now recommend creating a component directory to organise your repo now that it is beginning to get more functional.

Get a loading message in there for your comments' fetch and you're good to merge! 

Really good work this week! 

Styling is nice and is responsive enough to mobile. ++

2023-06-02 08:03 UTC, MrMcSnail commented on src/apis/api.js
> +export const fetchComments = (review_id) => {
Is it nit-picky of me to say this would be better named as `fetchCommentsById()`, or `fetchCommentsForReview()`, or `fetchCommentsByReviewId()`? Yeah probably nit-picking, but just immagine I'm a senior dev who has come to work after a terrible commute and an argument with their partner and has been kept up all night by their snotty, hot child and the neighbours dog.  🤷

2023-06-02 08:03 UTC, MrMcSnail commented on src/Comments.jsx
> +          if (obj === "nothing") {
Well done for accounting for reviews with no comments.

2023-06-02 08:03 UTC, MrMcSnail commented on src/Comments.jsx
> +  useEffect(() => {
I'm craving a loading state here for fetching of the comments themselves, with a relevant message for the user.

2023-06-02 08:53 UTC, merged